### ISSUE TITLE
Deprecate in favor of official Cloud Vision API clients

### ISSUE THREAD

**Issue by jmdobry** [tejitak/node-cloud-vision-api#7]
Thanks for making this client!

Now, [gcloud-node](https://googlecloudplatform.github.io/gcloud-node/#/docs/vision) and [google-api-nodejs-client](https://github.com/google/google-api-nodejs-client) both officially support the Cloud Vision API. For the best developer experience, these clients are the recommended way to use the Cloud Vision API in Node.js.

Please consider deprecating `node-cloud-vision-api` and pointing to the official clients:

```
npm deprecate node-cloud-vision-api "Deprecated in favor of official Cloud Vision API clients: https://github.com/GoogleCloudPlatform/gcloud-node and https://github.com/google/google-api-nodejs-client"
```

**Comment by tejitak** [comment]
@jmdobry Okay. I marked it as deprecated by running the command.
Now it should be deprecated like below.

```
> npm install --save node-cloud-vision-api
npm WARN deprecated node-cloud-vision-api@0.2.0: Deprecated in favor of official Cloud Vision API clients: https://github.com/GoogleCloudPlatform/gcloud-node and https://github.com/google/google-api-nodejs-client
```

**Comment by jmdobry** [comment]
Awesome, thank you for your support. Cheers!
